### PR TITLE
test: added unit test for file CommonServer/Middleware/UserAuthorization

### PR DESCRIPTION
**Pull request by beejay141**
### Title of this pull request?

- added unit test for file `CommonServer/Middleware/UserAuthorization.ts`

### Small Description?

- I added unit tests for file `UserAuthorization.ts` inside directory `CommonServer/Middleware directory`.
- The added unit test file is inside `CommonServer/Tests/Middleware`
- I refactored function `getUserMiddleware` inside `UserAuthorization.ts`. Broken the function down into sub-functions to improve its readability and testability.

### Pull Request Checklist: 

- [x] Please make sure all jobs pass before requesting a review. 
- [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
- [x] Have you lint your code locally before submission?
- [x] Did you write tests where appropriate?

### Related Issue?
closes https://github.com/OneUptime/oneuptime/issues/466

### CODE REVIEW

**Comment by beejay141** [comment]
@simlarsen 
I'd like to suggest that the method [getUserMiddleware](https://github.com/OneUptime/oneuptime/blob/639c4b13aeee9dd2c4abd1445d58839bd73f9dff/CommonServer/Middleware/UserAuthorization.ts#L112)  should be further broken down into sub functions  to improve the readability and testability of the method.

https://github.com/OneUptime/oneuptime/blob/639c4b13aeee9dd2c4abd1445d58839bd73f9dff/CommonServer/Middleware/UserAuthorization.ts#L112

**Comment by simlarsen** [comment]
@beejay141 can you please look into that as well?

**Comment by beejay141** [comment]
> @beejay141 Nice idea. can you please look into that as well?

Okay @simlarsen , let me give it a try.

**Comment by beejay141** [comment]
> @beejay141 Nice idea. can you please look into that as well?

@simlarsen This has been done.
https://www.loom.com/share/5abd086657084ea9823891ce21a50e8c

**Comment by simlarsen** [comment]
This seems to be breaking. Can you please run the project and try to log in and it will not log in.

**Review by simlarsen — CHANGES_REQUESTED** [review]
Breaking changes

**Comment by beejay141** [comment]
> Breaking changes

@simlarsen , this has been fixed. 
https://www.loom.com/share/58f49930aff9414ebb91479d27954604

**Review by simlarsen — APPROVED** [review]

**Pull request merged**
