### PR TITLE
Adds label column to probe

### LINKED ISSUE #814: Enhancement: Labels for probes
Probes should have labels just like everything else in one-time. This is particularly important from a security perspective to prevent other teams from using your team's probes.

### PR DESCRIPTION
**Pull request by hammadfauz**
### Pull Request Checklist: 

- [x] Please make sure all jobs pass before requesting a review. 
- [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
- [x] Have you lint your code locally before submission?
- [ ] Did you write tests where appropriate?

### CODE REVIEW

**Comment by hammadfauz** [comment]
@simlarsen

**Comment by simlarsen** [comment]
@hammadfauz we need to do a lot more things here, for example: Have labels column in the UI in Project Settings -> Probe

**Comment by simlarsen** [comment]
Tasks: 
 - You need to add a new column to Project Settings -> Probes for labels and make sure people who can add edit probes should also be able to add labels.

**Comment by simlarsen** [comment]
Closing this because of inactivity

**Pull request closed without merging**
